"""
utils/formatter.py
Format raw agent output into clean, readable sections.
"""

from datetime import datetime, timedelta


SEPARATOR = "─" * 50


def format_itinerary(raw_output: str) -> str:
    """
    Wrap raw agent output in a clean terminal-friendly format.
    Streamlit will use this same output and render it as markdown.
    """
    timestamp = datetime.now().strftime("%d %b %Y, %I:%M %p")
    header = f"\n{'═' * 50}\n✈  AI TRAVEL PLANNER — Generated {timestamp}\n{'═' * 50}\n"
    footer = f"\n{SEPARATOR}\n🤖 Plan generated by Agentic AI | Powered by LangChain\n{SEPARATOR}\n"
    return header + raw_output + footer


def format_budget_breakdown(flight: float, hotel_per_night: float, nights: int, daily: float) -> str:
    """Return a formatted budget breakdown string."""
    hotel_total = hotel_per_night * nights
    daily_total = daily * nights
    grand_total = flight + hotel_total + daily_total

    lines = [
        f"\n{SEPARATOR}",
        "💰 BUDGET BREAKDOWN",
        SEPARATOR,
        f"  ✈  Flight (round trip)   : ₹{flight:,.0f}",
        f"  🏨 Hotel ({nights} nights)      : ₹{hotel_total:,.0f}  (₹{hotel_per_night:,.0f}/night)",
        f"  🍽  Food & Local Travel   : ₹{daily_total:,.0f}  (₹{daily:,.0f}/day)",
        SEPARATOR,
        f"  💵 TOTAL ESTIMATED COST  : ₹{grand_total:,.0f}",
        SEPARATOR,
    ]
    return "\n".join(lines)


def format_day_plan(day_num: int, date: str, activities: list[str], weather: str) -> str:
    """Format a single day's itinerary."""
    lines = [
        f"\n📅 DAY {day_num} — {date}",
        f"   🌤  Weather: {weather}",
        "   Activities:",
    ]
    for i, act in enumerate(activities, 1):
        lines.append(f"     {i}. {act}")
    return "\n".join(lines)


def generate_date_range(start_date: str, num_days: int) -> list[str]:
    """
    Generate list of formatted date strings.
    start_date: 'YYYY-MM-DD'
    """
    try:
        start = datetime.strptime(start_date, "%Y-%m-%d")
        return [(start + timedelta(days=i)).strftime("%d %b %Y (%A)") for i in range(num_days)]
    except ValueError:
        return [f"Day {i+1}" for i in range(num_days)]